In [10]:
import pandas as pd
import re

In [88]:
dept_dict={'ENGH':'English',
'VB':'Pharma',
'MS':'Media',
'AAS' : 'Asian American Studies',
'ABE' : 'Agricultural and Biological Eng',
'ACCY' : 'Accountancy',
'ACE' : 'Agr & Consumer Economics',
'ACES' : 'Agr, Consumer, & Env Sciences',
'ADV' : 'Advertising',
'AE' : 'Aerospace Engineering',
'AFAS' : 'Air Force Aerospace Studies',
'AFRO' : 'African American Studies',
'AFST' : 'African Studies',
'AGCM' : 'Agricultural Communications',
'AGED' : 'Agricultural Education',
'AHS' : 'Applied Health Sci Courses',
'AIS' : 'American Indian Studies',
'ALEC' : 'Agricultural Leadership, Education, & Communications Program',
'ANSC' : 'Animal Sciences',
'ANTH' : 'Anthropology',
'ARAB' : 'Arabic',
'ARCH' : 'Architecture',
'ART' : 'Art',
'ARTD' : 'Art-Design',
'ARTE' : 'Art-Education',
'ARTF' : 'Art-Foundation',
'ARTH' : 'Art-History',
'ARTJ' : 'Japan House',
'ARTS' : 'Art-Studio',
'ASRM' : 'Actuarial Science & Risk Management',
'ASST' : 'Asian Studies',
'ASTR' : 'Astronomy',
'ATMS' : 'Atmospheric Sciences',
'AVI':"Aviation",
'BADM' : 'Business Administration',
'BASQ' : 'Basque',
'BCOG' : 'Brain and Cognitive Science',
'BCS' : 'Bosnian-Croatian-Serbian',
'BDI' : 'Business Data & Innovation',
'BIOC' : 'Biochemistry',
'BIOE' : 'Bioengineering',
'BIOL' : 'Biology',
'BIOP' : 'Biophysics',
'BSE' : 'Biomedical Sciences and Engineering',
'BTW' : 'Business and Technical Writing',
'BULG' : 'Bulgarian',
'BUS' : 'Business',
'CAS' : 'Center for Advanced Study',
'CATL' : 'Catalan',
'CB' : 'Comparative Biosciences',
'CDB' : 'Cell and Developmental Biology',
'CEE' : 'Civil and Environ Engineering',
'CHBE' : 'Chemical and Biomolecular Engineering',
'CHEM' : 'Chemistry',
'CHIN' : 'Chinese',
'CHLH' : 'Community Health',
'CHP': 'Campus Honors Program',
'CIC' : 'Committee on Inst Cooperation',
'CI' : 'Curriculum and Instruction',
'CINE':"Cinema",
'CLCV' : 'Classical Civilization',
'CLE' : 'Clinical Sciences and Engineering',
'CMN' : 'Communication',
'CPSC' : 'Crop Sciences',
'CS' : 'Computer Science',
'CSE' : 'Computational Science and Engineering',
'CW' : 'Creative Writing',
'CWL' : 'Comparative & World Literature',
'CZCH' : 'Czech',
'DANC' : 'Dance',
'DTX' : 'Human-Centered Design & Design Thinking',
'EALC' : 'East Asian Languages & Cultures',
'ECE' : 'Electrical and Computer Engineering',
'ECON' : 'Economics',
'EDPR' : 'Educational Practice',
'EDUC' : 'Education',
'EIL' : 'English as an Intl Language',
'ENG' : 'Engineering',
'ENGL' : 'English',
'ENSU' : 'Environmental Sustainability',
'ENT' : 'Entomology',
'ENVS' : 'Environmental Studies',
'EOL' : 'Educ Organization & Leadership',
'EPOL' : 'Ed Policy, Org & Ldership',
'EPS' : 'Educational Policy Studies',
'EPSY' : 'Educational Psychology',
'ERAM' : 'Education Research and Methods',
'ESE' : 'Earth, Society, & Environment',
'ESL' : 'English as a Second Language',
'ETMA': 'Engineering Technology & Management for Agricultural Systems',
'EURO' : 'European Union Studies',
'FAA' : 'Fine and Applied Arts',
'FIN' : 'Finance',
'FLTE' : 'Foreign Language Teacher Education',
'FR' : 'French',
'FSHN' : 'Food Science & Human Nutrition',
'GC' : 'Graduate College',
'GCL':'Graduate College',
'GEOL' : 'Geology',
'GE':'General Engineering',
'GER' : 'German',
'GEOG' : 'Geography & Geographic Information Science',
'GLBL' : 'Global Studies',
'GMC' : 'Germanic',
'GRK' : 'Greek',
'GRKM' : 'Modern Greek',
'GSD' : 'Game Studies and Design',
'GS' : 'General Studies',
'GWS': 'Gender and Women Studies',
'HDES' : 'Human Dimensions of Env Sys',
'HDFS' : 'Human Dev and Family Studies',
'HEBR' : 'Hebrew, Modern and Classical',
'HIST' : 'History',
'HNDI' : 'Hindi',
'HORT' : 'Horticulture',
'HRD' : 'Human Resource Development',
'HRE':"Human Resources",
'HT' : 'Health Technology',
'HUM' : 'Humanities Courses',
'IB' : 'Integrative Biology',
'IE' : 'Industrial Engineering',
'IHLT' : 'IHealth',
'INFO' : 'Informatics',
'IS' : 'Information Sciences',
'ITAL' : 'Italian',
'JAPN' : 'Japanese',
'JOUR' : 'Journalism',
'JS' : 'Jewish Studies',
'KIN' : 'Kinesiology',
'KOR' : 'Korean',
'LA' : 'Landscape Architecture',
'LAS' : 'Liberal Arts and Sciences',
'LAST' : 'Latin American & Caribbean St',
'LAT' : 'Latin',
'LAW' : 'Law',
'LCTL' : 'Less Commonly Taught Languages',
'LEAD' : 'Organizational & Community Leadership',
'LER' : 'Labor and Employment Relations',
'LGLA' : 'Lingala',
'LING' : 'Linguistics',
'LLS' : 'Latina/Latino Studies',
'MACS' : 'Media and Cinema Studies',
'MATH' : 'Mathematics',
'MBA' : 'MBA Program',
'MCB' : 'Molecular and Cell Biology',
'MDIA' : 'Media',
'MDVL' : 'Medieval Studies',
'ME' : 'Mechanical Engineering',
'MFST' : 'Metropolitan Food & Environmental Systems',
'MICR' : 'Microbiology',
'MILS' : 'Military Science',
'MIP' : 'Moleculr & Integrative Physiology',
'MSE' : 'Materials Science & Engineering',
'MSP' : 'Medical Scholars Program',
'MUSC' : 'Music Lessons and Ensembles',
'MUSE' : 'Museum Studies',
'MUS' : 'Music',
'NE' : 'Neural Engineering',
'NEUR' : 'Neuroscience',
'NPRE' : 'Nuclear, Plasma, Radiological Engineering',
'NRES' : 'Natural Resources & Environ Sc',
'NS' : 'Naval Science',
'NUTR' : 'Nutritional Sciences',
'PATH' : 'Pathobiology',
'PBIO' : 'Plant Biology',
'PERS' : 'Persian',
'PHIL' : 'Philosophy',
'PHYS' : 'Physics',
'PLPA' : 'Plant Pathology',
'POL' : 'Polish',
'PORT' : 'Portuguese',
'PSM' : 'Professional Science Master',
'PS' : 'Political Science',
'PSYC' : 'Psychology',
'QUEC' : 'Quechua',
'REES' : 'Russian, East European and Eurasian Studies',
'REHB' : 'Rehabilitation Counseling',
'REL' : 'Religion',
'RLST':'Religion',
'RHET' : 'Rhetoric and Composition',
'RMLG' : 'Romance Linguistics',
'RST' : 'Recreation, Sport, and Tourism',
'RUSS' : 'Russian',
'RSOC':"Rural Society",
'SAME' : 'South Asian & Middle Eastern',
'SBC' : 'Strategic Brand Communication',
'SCAN' : 'Scandinavian',
'SCR':'South Slavic Studies',
'SE' : 'Systems Engineering and Design',
'SHS' : 'Speech and Hearing Science',
'SLAV' : 'Slavic',
'SLCL' : 'Literatures Cultures Linguistics',
'SNSK' : 'Sanskrit',
'SOC' : 'Sociology',
'SOCW' : 'Social Work',
'SPAN' : 'Spanish',
'SPED' : 'Special Education',
'STAT' : 'Statistics',
'SWAH' : 'Swahili',
'TAM' : 'Theoretical and Applied Mechanics',
'TE' : 'Technology Entrepreneurship',
'THEA' : 'Theatre',
'TMGT' : 'Technology and Management',
'TRST' : 'Translation Studies',
'TSM' : 'Technical System Management',
'TURK' : 'Turkish',
'UKR' : 'Ukrainian',
'UP' : 'Urban and Regional Planning',
'VCM' : 'Veterinary Clinical Medicine',
'VM' : 'Veterinary Medicine Courses',
'WGGP' : 'Women and Gender in Global Perspectives',
'WLOF' : 'Wolof',
'WRIT' : 'Writing Studies',
'YDSH' : 'Yiddish',
'ZULU' : 'Zulu',
'SLS':"Student Legal Service"}

In [89]:
courses=pd.read_csv('Courses_table.csv',index_col=0)

In [90]:
courses.head()

,CRN,Title,Description
0,AAS100,Intro Asian American Studies,Interdisciplinary introduction to the basic co...
1,AAS105,Introduction to Arab American Studies,Interdisciplinary introduction to the basic co...
2,AAS120,Intro to Asian Am Pop Culture,Introductory understanding of the way U.S. pop...
3,AAS199,Undergraduate Open Seminar,May be repeated to a maximum of 6 hours.
4,AAS200,U.S. Race and Empire,Invites students to examine histories and narr...

In [91]:
courses['DepartmentId']=''

In [92]:
for i in range(len(courses)):
    CRN=courses.iloc[i,0]
    res = re.findall('([a-zA-Z ]*)\d*.*', CRN)
    courses.iloc[i,-1]=str(res[0])

In [94]:
courses.to_csv('Courses.csv',index=False)

In [75]:
Department=pd.DataFrame(data=list(dept_dict.keys()),columns=['DepartmentId'])

In [76]:
Department['DepartmentName']=list(dept_dict.values())

In [77]:
Department.sort_values('DepartmentId',inplace=True)

In [78]:
Department.reset_index(inplace=True,drop=True)

In [56]:
Department.rename(columns={'index':'DepartmentId','Department':'DepartmentName'},inplace=True)

In [80]:
Department.to_csv('Department.csv',index=False)

In [81]:
cs

    DepartmentId                           DepartmentName
0            AAS                   Asian American Studies
1            ABE          Agricultural and Biological Eng
2           ACCY                              Accountancy
3            ACE                 Agr & Consumer Economics
4           ACES            Agr, Consumer, & Env Sciences
..           ...                                      ...
211         WGGP  Women and Gender in Global Perspectives
212         WLOF                                    Wolof
213         WRIT                          Writing Studies
214         YDSH                                  Yiddish
215         ZULU                                     Zulu

[216 rows x 2 columns]

In [82]:
courses.to_CSV

,CRN,Title,Description,Department
0,AAS100,Intro Asian American Studies,Interdisciplinary introduction to the basic co...,Asian American Studies
1,AAS105,Introduction to Arab American Studies,Interdisciplinary introduction to the basic co...,Asian American Studies
2,AAS120,Intro to Asian Am Pop Culture,Introductory understanding of the way U.S. pop...,Asian American Studies
3,AAS199,Undergraduate Open Seminar,May be repeated to a maximum of 6 hours.,Asian American Studies
4,AAS200,U.S. Race and Empire,Invites students to examine histories and narr...,Asian American Studies
...,...,...,...,...
8584,ZULU202,Elementary Zulu II,Continuation of ZULU 201 with introduction of ...,Zulu
8585,ZULU403,Intermediate Zulu I,Survey of more advanced grammar; emphasis on i...,Zulu
8586,ZULU404,Intermediate Zulu II,Continuation of ZULU 403; emphasis on increasi...,Zulu
8587,ZULU405,Advanced Zulu I,Third year Zulu with emphasis on conversationa...,Zulu
8588,ZULU406,Advanced Zulu II,Continuation of Zulu 405 with increased emphas...,Zulu